# Generated by Django 6.0.6 on 2026-06-22 01:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nickname', models.CharField(max_length=50, unique=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('age_group', models.CharField(blank=True, choices=[('10대', '10대'), ('20대', '20대'), ('30대', '30대'), ('40대', '40대'), ('50대 이상', '50대 이상')], max_length=20, null=True)),
                ('monthly_saving', models.PositiveIntegerField(blank=True, help_text='월 저축 가능 금액, 단위: 만원', null=True)),
                ('investment_type', models.CharField(blank=True, choices=[('CONSERVATIVE', '안정형'), ('MODERATE', '중립형'), ('AGGRESSIVE', '공격형')], max_length=20, null=True)),
                ('preferred_product_type', models.CharField(blank=True, choices=[('DEPOSIT', '예금'), ('SAVING', '적금'), ('BOTH', '상관없음')], max_length=10, null=True)),
                ('financial_goal', models.CharField(blank=True, max_length=100, null=True)),
                ('target_amount', models.PositiveIntegerField(blank=True, help_text='단위: 만원', null=True)),
                ('investment_period', models.PositiveIntegerField(blank=True, help_text='단위: 개월', null=True)),
                ('provider', models.CharField(choices=[('LOCAL', '일반'), ('KAKAO', '카카오')], default='LOCAL', max_length=10)),
                ('provider_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
    ]
