# Generated by Django 6.0.6 on 2026-06-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='monthly_income',
        ),
        migrations.AddField(
            model_name='user',
            name='monthly_saving',
            field=models.PositiveIntegerField(blank=True, help_text='월 저축 가능 금액, 단위: 만원', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_product_type',
            field=models.CharField(blank=True, choices=[('DEPOSIT', '예금'), ('SAVING', '적금'), ('BOTH', '상관없음')], max_length=10, null=True),
        ),
    ]
