# Generated by Django 6.0.6 on 2026-06-23 01:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_co_no', models.CharField(max_length=20, verbose_name='금융회사 코드')),
                ('kor_co_nm', models.CharField(max_length=100, verbose_name='금융회사명')),
                ('fin_prdt_cd', models.CharField(max_length=50, unique=True, verbose_name='금융상품코드')),
                ('fin_prdt_nm', models.CharField(max_length=200, verbose_name='금융상품명')),
                ('product_type', models.CharField(choices=[('D', '정기예금'), ('S', '정기적금')], max_length=1, verbose_name='상품유형')),
                ('join_way', models.CharField(blank=True, max_length=200, verbose_name='가입방법')),
                ('join_member', models.CharField(blank=True, max_length=200, verbose_name='가입대상')),
                ('join_deny', models.CharField(blank=True, max_length=10, verbose_name='가입제한')),
                ('spcl_cnd', models.TextField(blank=True, verbose_name='우대조건')),
                ('etc_note', models.TextField(blank=True, verbose_name='기타 유의사항')),
                ('mtrt_int', models.TextField(blank=True, verbose_name='만기 후 이자율')),
                ('max_limit', models.BigIntegerField(blank=True, null=True, verbose_name='최고한도')),
                ('rsrv_type', models.CharField(blank=True, max_length=10, verbose_name='적립유형코드')),
                ('rsrv_type_nm', models.CharField(blank=True, max_length=50, verbose_name='적립유형명')),
                ('dcls_strt_day', models.CharField(blank=True, max_length=8, verbose_name='공시 시작일')),
                ('dcls_end_day', models.CharField(blank=True, max_length=8, null=True, verbose_name='공시 종료일')),
                ('fin_co_subm_day', models.CharField(blank=True, max_length=12, verbose_name='금융회사 제출일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='최초 저장일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='마지막 갱신일')),
            ],
            options={
                'verbose_name': '금융상품',
                'verbose_name_plural': '금융상품 목록',
                'db_table': 'financial_product',
            },
        ),
        migrations.CreateModel(
            name='UserProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='products.financialproduct', verbose_name='상품')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='회원')),
            ],
            options={
                'verbose_name': '관심상품',
                'verbose_name_plural': '관심상품 목록',
                'db_table': 'favorite_product',
                'unique_together': {('user', 'product')},
            },
        ),
        migrations.AddField(
            model_name='financialproduct',
            name='liked_users',
            field=models.ManyToManyField(blank=True, related_name='liked_products', through='products.UserProduct', to=settings.AUTH_USER_MODEL, verbose_name='찜한 사용자'),
        ),
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intr_rate_type', models.CharField(choices=[('S', '단리'), ('M', '복리')], max_length=1, verbose_name='금리유형코드')),
                ('intr_rate_type_nm', models.CharField(blank=True, max_length=20, verbose_name='금리유형명')),
                ('rsrv_type', models.CharField(blank=True, max_length=1, verbose_name='적립유형코드')),
                ('rsrv_type_nm', models.CharField(blank=True, max_length=20, verbose_name='적립유형명')),
                ('save_trm', models.IntegerField(verbose_name='저축기간(개월)')),
                ('intr_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='기본금리')),
                ('intr_rate2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='최고금리')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='products.financialproduct', verbose_name='금융상품')),
            ],
            options={
                'verbose_name': '상품 금리 옵션',
                'verbose_name_plural': '상품 금리 옵션 목록',
                'db_table': 'product_option',
                'unique_together': {('product', 'intr_rate_type', 'rsrv_type', 'save_trm')},
            },
        ),
    ]
