# Generated by Django 6.0.6 on 2026-06-23 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialproduct',
            name='rsrv_type',
        ),
        migrations.RemoveField(
            model_name='financialproduct',
            name='rsrv_type_nm',
        ),
        migrations.AddField(
            model_name='financialproduct',
            name='dcls_month',
            field=models.CharField(blank=True, max_length=6, verbose_name='공시 제출월'),
        ),
    ]
