# Generated by Django 6.0.6 on 2026-06-22 01:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kakao_id', models.CharField(max_length=50)),
                ('place_name', models.CharField(max_length=100)),
                ('road_address_name', models.CharField(blank=True, max_length=200, null=True)),
                ('address_name', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_banks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'kakao_id')},
            },
        ),
    ]
