# Generated by Django 6.0.6 on 2026-06-24 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('FREE', '자유'), ('DEPOSIT', '예금·적금'), ('EXCHANGE', '환율·해외'), ('STOCK', '주식·ETF'), ('REALESTATE', '부동산'), ('QNA', '질문')], default='FREE', max_length=20),
        ),
    ]
