# Generated by Django 6.0.6 on 2026-06-23 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(max_length=10)),
                ('currency_name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('deal_bas_r', models.FloatField()),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('currency_code', 'date')},
            },
        ),
    ]
